spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: movement-service
          uri: lb://movement-service
          predicates:
            - Path=/movement/**
          filters:
            - RewritePath=/movement/(?<segment>.*), /$\\{segment}
        - id: rules-service
          uri: lb://rules-service
          predicates:
            - Path=/rules/**
          filters:
            - RewritePath=/rules/(?<segment>.*), /$\\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
