spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: movement-service
          uri: lb://movement-service
          predicates:
            - Path=/movement-service/**
          filters:
            - RewritePath=/movement-service/(?<segment>.*), /$\\{segment}
        - id: rules-service
          uri: lb://rules-service
          predicates:
            - Path=/rules-service/**
          filters:
            - RewritePath=/rules-service/(?<segment>.*), /$\\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8080
