spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - HEAD
              - PUT
              - DELETE
              - PATCH
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: movement-service
          uri: lb://movement-service
          predicates:
            - Path=/movement-service/**
          filters:
            - StripPrefix=1
        - id: rules-service
          uri: lb://rules-service
          predicates:
            - Path=/rules-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8080
