server:
  port: 8761

spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false